Add compat with hls.js v1
Novage/p2p-media-loader pull request #178
Opened 2021-02-24 12:53 UTC by Chocobozzz

2021-02-28 17:08 UTC, askz commented
up !

Is the project dead?

2021-03-05 19:46 UTC, hoangvietfreelancer commented
Thanks for adding support for hls.js v1!
It's all working if I add non-AES encrypt content to JWPlayer.
But when add AES encrypt to JWPlayer, I got this problem:
```
Uncaught TypeError: n.onProgress is not a function
    at r.HlsJsLoader.successSegment (p2p-media-loader-hlsjs.min.js:formatted:208)
    at p2p-media-loader-hlsjs.min.js:formatted:165
```

2021-03-06 13:26 UTC, hoangvietfreelancer commented on p2p-media-loader-hlsjs/lib/hlsjs-loader.ts
> +        callbacks.onProgress(this.stats, context, content);
```suggestion
        if(callbacks.onProgress) {
            callbacks.onProgress(this.stats, context, content);
        }
```
AES key file does not require onProgress callback so adding this check will prevent ```onProgress is not a function``` error

2021-03-08 18:25 UTC, Teranode commented
Have you tested this with debug enabled?

2021-03-10 13:43 UTC, hoangvietfreelancer requested changes
hls.js v1 add ```rangeStart: 0``` and ```rangeEnd: 0``` to xhr as default instead of nothing(undefined) so we need to change this line:
https://github.com/Novage/p2p-media-loader/blob/e661cabde09f2790ac12d5b499f980fba2467b42/p2p-media-loader-hlsjs/lib/hlsjs-loader.ts#L72
to
```typescript
((context.rangeStart == undefined) || (context.rangeEnd == undefined)) || (context.rangeStart === 0 && context.rangeEnd === 0)
```
to make it work with p2p(otherwise, it only use HTTP)

2021-03-10 14:40 UTC, Chocobozzz commented
Thanks @hoangvietfreelancer, I updated the PR. Please test and tell me if it's working on your side.

2021-03-30 23:41 UTC, mrlika commented
> up !
> 
> Is the project dead?

No! It is still moving! But very slow during last year...

@Chocobozzz, thanks for the PR. I am reviewing hls.js v1 support now. I slightly improved types usage for hls.js < v1 which makes further development and support more reliable. I will try to do it in a similar way for v1 taking this PR as a reference implementation.

2021-04-05 09:50 UTC, piranna commented
If I can help to move this fordward, just tell me :-)

2021-04-05 11:48 UTC, mrlika commented
@piranna , you can help by testing this branch:

https://github.com/Novage/p2p-media-loader/tree/feat/hlsjs1

it implements almost the same approach as in this PR but applied to the latest code that uses hls.js type definitions.

2021-04-05 12:07 UTC, piranna commented
> @piranna , you can help by testing this branch:

Great, I'll take a look :-)

2021-04-12 14:38 UTC, Chocobozzz commented
Closing now it's being worked on a dedicated branch. Thanks @mrlika

2021-04-12 14:38 UTC, closed without merging

2021-04-12 15:11 UTC, mrlika commented
@Chocobozzz ,  it mostly works but for some reason bitrate/quality is chosen lower than it should be even when hard-coded to a max value. Requires time to investigate why.

2021-04-14 08:08 UTC, Chocobozzz commented
May be related to recent prettier/eslint changes on master. You renamed `byterange` to `byteRange` but `m3u8-parser` returns segments with `byterange` property.

2021-04-23 07:00 UTC, kontrollanten commented
@mrlika Is everything working now that #202 is merged? Is there anything I can do to help releasing hls.js v1 support?

2021-04-25 11:57 UTC, mrlika commented
@kontrollanten, it works with issues. You can join the development: https://github.com/Novage/p2p-media-loader/pull/203