Parse playlists and identify them by loaded segments.
Novage/p2p-media-loader pull request #288
Opened 2023-06-09 13:38 UTC by i-zolotarenko

2023-06-12 08:10 UTC, mrlika reviewed
> This branch has conflicts that must be resolved

Please resolve conflicts

2023-06-12 08:10 UTC, mrlika commented on packages/p2p-media-loader-hlsjs/src/services/segment-mananger.ts
> +  type Segment as ParserSegment,
No need for type specification here

2023-06-12 08:15 UTC, mrlika reviewed
`p2p-media-loader-demo` has compile errors

2023-06-12 08:59 UTC, mrlika requested changes

2023-06-12 08:59 UTC, mrlika commented on packages/p2p-media-loader-hlsjs/src/services/fragment-loader.ts
> +        // console.log(playlist);
Don't commit comments

2023-06-12 08:59 UTC, mrlika commented on packages/p2p-media-loader-hlsjs/src/services/segment-mananger.ts
> +  }
`undefined` is usually better than `null`. For example, the requirement for developers who create TypeScript language: https://github.com/Microsoft/TypeScript/wiki/Coding-guidelines#null-and-undefined

2023-06-12 08:59 UTC, mrlika commented on packages/p2p-media-loader-hlsjs/src/services/segment-mananger.ts
> +class TypeGuard {
No need in TypeGuard class to use it as  a namespace

2023-06-12 08:59 UTC, mrlika commented on packages/p2p-media-loader-hlsjs/src/services/segment-mananger.ts
> +    parser.end();
Would you happen to know how errors are handled?

2023-06-12 08:59 UTC, mrlika commented on packages/p2p-media-loader-hlsjs/src/services/segment-mananger.ts
> +  audioPlaylists: AudioPlaylistsContainer = new AudioPlaylistsContainer();
Consider refactoring (simplify) to a map that contains both video and audio playlists: `playlists: Map<string, Playlist>` without abstract classes and inheritance

2023-06-14 13:18 UTC, mrlika requested changes

2023-06-14 13:25 UTC, mrlika requested changes

2023-06-14 13:25 UTC, mrlika commented on packages/p2p-media-loader-hlsjs/src/services/playlist.ts
> +    this.id = manifestUrl ? `${manifestUrl}-${type}-V${index}` : this.url;
Use the base part of `manifestUrl` and `this.url` without `?`

2023-06-14 13:36 UTC, mrlika requested changes

2023-06-14 13:36 UTC, mrlika commented on packages/p2p-media-loader-hlsjs/src/services/segment-mananger.ts
> +      }
```suggestion
      let playlist = this.playlists.get(responseUrl);

      if (!playlist && !this.manifest) {
        playlist = new Playlist({
          type: "unknown",
          url: responseUrl,
          manifestUrl: this.manifestUrl,
          mediaSequence,
          index: -1,
        });
        this.playlists.set(responseUrl, playlist);
        }
      }
      
      if (playlist) playlist.setSegments(segments);
```

2023-06-15 07:21 UTC, i-zolotarenko commented on packages/p2p-media-loader-hlsjs/src/services/playlist.ts
> +import { Segment as ParserSegment } from "m3u8-parser";
Actually I have the Segment class in this file so I have to rename this import.

2023-06-15 10:37 UTC, i-zolotarenko commented on packages/p2p-media-loader-hlsjs/src/services/segment-mananger.ts
> +import { MasterManifest, Parser } from "m3u8-parser";
Can I investigate it later? I guess its behavior probably depends on certain player.

2023-06-15 11:40 UTC, mrlika approved these changes

2023-06-15 11:57 UTC, mrlika requested changes

2023-06-15 11:57 UTC, mrlika commented on packages/p2p-media-loader-hlsjs/src/services/playlist.ts
> +  }
```suggestion
    this.type = type;
    this.index = index;
    this.url = new URL(url, manifestUrl?.response).toString();
    this.id = manifestUrl?.request
      ? `${getUrlWithoutParameters(manifestUrl.request)}-${type}-V${index}`
      : getUrlWithoutParameters(this.url);
    this.mediaSequence = mediaSequence;
  }

  setSegments(segments: ParserSegment[]) {
    const mapEntries = segments.map<[string, Segment]>((s) => {
      const segment = new Segment(s.uri, this.url, s.byterange);
      return [segment.localId, segment];
    });
    this.segmentsMap = new Map(mapEntries);
  }
```

2023-06-15 14:54 UTC, mrlika approved these changes

2023-06-15 14:54 UTC, merged