Create simple shaka player plugin.
Novage/p2p-media-loader pull request #291
Opened 2023-06-21 14:15 UTC by i-zolotarenko

2023-07-03 11:14 UTC, mrlika requested changes

2023-07-03 11:14 UTC, mrlika commented on packages/p2p-media-loader-shaka/src/services/engine.ts
Test stop/start for Shaka and Hls.js instances. Add logs

2023-07-03 11:17 UTC, mrlika requested changes

2023-07-03 11:17 UTC, mrlika commented on packages/p2p-media-loader-shaka/src/services/manifest-parser-decorator.ts
Test network issues

2023-07-03 11:23 UTC, mrlika requested changes

2023-07-03 11:23 UTC, mrlika commented on packages/p2p-media-loader-shaka/src/services/engine.ts
Add the ability to pass Shaka module

2023-07-03 13:14 UTC, i-zolotarenko commented on packages/p2p-media-loader-hlsjs/src/services/segment-mananger.ts
> +      const mediaSequence = manifest.mediaSequence || 1;
I will fix it later when rewrite p2pml-hlsjs without m3u8-parser.

2023-07-05 13:56 UTC, mrlika requested changes

2023-07-05 13:56 UTC, mrlika commented on p2p-media-loader-demo/src/App.tsx
> +    // const url = videoUrl.live2;
Remove

2023-07-05 13:56 UTC, mrlika commented on packages/p2p-media-loader-hlsjs/src/index.ts
> +// eslint-disable-next-line spaced-comment
Remove comment

2023-07-05 13:56 UTC, mrlika commented on p2p-media-loader-demo/src/declarations.d.ts
> +// declare module "shaka-player";
Remove comment

2023-07-05 13:56 UTC, mrlika commented on packages/p2p-media-loader-shaka/src/types/types.d.ts
> +export type Shaka = {
Try
```suggestion
export type Shaka = typeof window.shaka;
```

2023-07-05 14:09 UTC, mrlika approved these changes

2023-07-05 14:13 UTC, merged