P2p loader.
Novage/p2p-media-loader pull request #305
Opened 2023-09-18 15:36 UTC by i-zolotarenko

2023-10-27 10:50 UTC, mrlika requested changes

2023-10-27 10:50 UTC, mrlika commented on packages/p2p-media-loader-core/src/p2p-loader.ts
> +    }, 0);
```suggestion
    if (this.isAnnounceMicrotaskCreated) return;
    
    this.isAnnounceMicrotaskCreated = true;

    queueMicrotask(() => {
      this.updateSegmentAnnouncement();
      this.broadcastSegmentAnnouncement();
      this.isAnnounceMicrotaskCreated = false;
    });
```

2023-10-31 10:08 UTC, i-zolotarenko commented on packages/p2p-media-loader-core/src/http-loader.ts
> +async function* readStream(
It's actually necessary, because the  ReadableStreamDefaultReader itself isn't AsyncGenerator and can't be used in for await ...

2023-10-31 10:32 UTC, i-zolotarenko commented on packages/p2p-media-loader-core/src/request.ts
Each hybrid loader has own request container.

2023-11-02 09:29 UTC, mrlika approved these changes

2023-11-02 09:33 UTC, merged