Resuming segment downloading.
Novage/p2p-media-loader pull request #320
Opened 2023-12-21 18:18 UTC by i-zolotarenko

2023-12-27 17:02 UTC, mrlika requested changes

2023-12-29 11:44 UTC, i-zolotarenko commented on packages/p2p-media-loader-core/src/core.ts
> +    maxPeerNotReceivingBytesTimeoutErrors: 3,
Peer bytes mismatch error will be thrown.

2023-12-29 14:20 UTC, mrlika commented on packages/p2p-media-loader-core/src/http-loader.ts
> +      if (response.status === 200) {
```suggestion
      if (response.status === 200 && !request.segment.byteRange) {
```

2023-12-29 14:36 UTC, mrlika approved these changes

2023-12-29 14:36 UTC, mrlika commented on packages/p2p-media-loader-core/src/http-loader.ts
> +      if (response.status === 200) {
```suggestion
      if (response.status === 200 && request.segment.byteRange) {
```

2023-12-29 14:36 UTC, mrlika commented on packages/p2p-media-loader-core/src/hybrid-loader.ts
> +        now - request.failedAttempts.lastClearTimestamp >
Use last failed attempt timestamp

2023-12-29 15:33 UTC, merged