Feat: setup http request callback
Novage/p2p-media-loader pull request #344
Opened 2024-03-01 14:39 UTC by DimaDemchenko

2024-03-01 15:17 UTC, mrlika requested changes

2024-03-01 15:17 UTC, mrlika commented on packages/p2p-media-loader-core/src/http-loader.ts
> +        request,
`Request` object can't be configured as far as I know. As discussed, did you test the solution by adding an arbitrary header?

2024-03-01 15:20 UTC, mrlika requested changes

2024-03-01 15:20 UTC, mrlika commented on packages/p2p-media-loader-core/src/http-loader.ts
> +      );
The parameter list should be better structured. `URL` and `byte range` should follow as they describe segment location.

```suggestion
        segment.url,
        request,
        this.byteRange as ByteRange,
      );
```

2024-03-01 18:04 UTC, mrlika commented on packages/p2p-media-loader-core/src/http-loader.ts
> +        request,
What about `credentials` field? It can be definitely set via init constructor parameter but looks like can't be changed on `Request` object

2024-03-01 18:08 UTC, mrlika commented on packages/p2p-media-loader-core/src/http-loader.ts
> +        request,
This code prints `same-origin`:
```js
const myRequest = new Request("flowers.jpg");
myRequest.credentials = 'omit';
console.log(myRequest.credentials);
```
But this code prints `omit`:
```js
const myRequest = new Request("flowers.jpg", {
  credentials: 'omit'
});
console.log(myRequest.credentials);
```

2024-03-01 18:23 UTC, mrlika requested changes

2024-03-01 18:23 UTC, mrlika commented on packages/p2p-media-loader-core/src/http-loader.ts
> +        this.byteRange as ByteRange,
byteRange can be undefined here. Using `as` is usually a hack that breaks types.

2024-03-05 07:23 UTC, mrlika requested changes

2024-03-05 07:36 UTC, mrlika requested changes

2024-03-05 07:36 UTC, mrlika commented on packages/p2p-media-loader-core/src/types.d.ts
> +  ) => Request;
```suggestion
  httpRequestSetup?: (
    segmentUrl: string,
    segmentByteRange: ByteRange | undefined,
    requestByteRange: { start: number; end?: number } | undefined,
  ) => Promise<Request | undefined | null>;
```

2024-03-05 07:36 UTC, mrlika commented on packages/p2p-media-loader-core/src/http-loader.ts
> +    const { requestByteRange: byteRange } = this;
Don't rename
```suggestion
    const { requestByteRange } = this;
```

2024-03-05 08:55 UTC, DimaDemchenko commented
Code below works fine. it loads video 10/10 times
```
httpRequestSetup: async (
      url: string,
      segmentByteRange: ByteRange | undefined,
      requestByteRange: { start: number; end?: number } | undefined,
    ) => {
      await new Promise((resolve) => {
        setTimeout(resolve, 1500);
      });

      const headers = new Headers(
        requestByteRange
          ? {
              Range: `bytes=${requestByteRange.start}-${
                requestByteRange.end ?? ""
              }`,
            }
          : undefined,
      );

      return new Request(url, {
        headers,
      });
    },

```


The implementation of func below works weird. It works only if time in settimeout is less than 1000.
It might be due to  httpNotReceivingBytesTimeoutMs: 1000, because when i change it to 2000, code works fine even with settimeout with 1500 ms. 

```
httpRequestSetup: async (
      url: string,
      segmentByteRange: ByteRange | undefined,
      requestByteRange: { start: number; end?: number } | undefined,
    ) => {
      await new Promise((resolve) => {
        setTimeout(resolve, 1000);
      });

      return null;
    },
```

2024-03-05 09:53 UTC, mrlika requested changes

2024-03-05 11:31 UTC, merged