Feat: players
Novage/p2p-media-loader pull request #361
Opened 2024-04-25 12:55 UTC by DimaDemchenko

2024-04-25 13:19 UTC, DimaDemchenko commented on packages/p2p-media-loader-demo/src/declaration.d.ts
> +}
should we keep this? Clappr doesn't have types

2024-04-25 14:45 UTC, DimaDemchenko commented on packages/p2p-media-loader-demo/src/declaration.d.ts
> +export {};
it seems like I declared right type for Hls, but I get TS errors across all files where window.Hls is used.
I can't find a good solution to those errors: " error TS2339: Property 'Hls' does not exist on type 'Window & typeof globalThis'."

```  
 // @ts-ignore
 window.Hls = HlsJsP2PEngine.injectMixin(Hls);
...
 // @ts-ignore
window.Hls = undefined;
 ```

2024-05-10 09:20 UTC, mrlika requested changes

2024-05-10 09:20 UTC, mrlika commented on packages/p2p-media-loader-demo/src/components/players/hlsjs/HlsjsVidstack.tsx
> +              configureHlsP2PEngineEvents({
subscribeToUiEvents

2024-05-10 12:03 UTC, mrlika approved these changes

2024-05-10 12:03 UTC, merged