Refactor: commands
Novage/p2p-media-loader pull request #392
Opened 2024-07-12 13:34 UTC by DimaDemchenko

2024-07-16 08:40 UTC, mrlika requested changes

2024-07-16 08:40 UTC, mrlika commented on packages/p2p-media-loader-core/src/core.ts
> +    httpNotReceivingBytesTimeoutMs: 3000,
Please retest the new default values

2024-07-16 08:40 UTC, mrlika commented on packages/p2p-media-loader-core/src/p2p/commands/types.ts
> +  r?: number; // request id
Make `r` required for all the commands

2024-07-16 08:40 UTC, mrlika commented on packages/p2p-media-loader-core/src/p2p/peer.ts
> +          this.downloadingContext?.request.segment.externalId === command.i ||
Change to `&&`

2024-07-17 09:59 UTC, mrlika approved these changes

2024-07-17 10:00 UTC, merged

2024-07-19 13:37 UTC, Chocobozzz commented
Hi,

Can you detail this protocol change? Is the purpose to resend a P2P request to the same peer for the same segment?

2024-07-19 14:07 UTC, mrlika commented
Hi, @Chocobozzz,

There were issues handling segment requests via P2P when a segmented download was canceled and restarted immediately. To address this, a randomly generated request ID is now added to the segment request command.

Fortunately, the library is designed so that P2P protocol version changes are minor because the protocol version is added to the WebTorrent info hash: https://github.com/Novage/p2p-media-loader/blob/0972c005958df549f3b27b8da0b6bf721450969c/packages/p2p-media-loader-core/src/utils/stream.ts#L23

This means that swarms consist of peers of the same protocol version. If peers of different protocol versions download the same stream, they will be in separate swarms, eliminating the ability for non-compatible communications.

2024-07-22 07:02 UTC, Chocobozzz commented
Thank you for your answer @mrlika :pray: 

Yes I was aware about the protocol version, we correctly handle it :) https://github.com/Chocobozzz/PeerTube/blob/fbee171a0bea725e74ddc9ca4a00875c2250afd4/server/core/lib/hls.ts#L27