Add missing data param in segment validator
Novage/p2p-media-loader pull request #426
Opened 2024-10-24 14:16 UTC by Chocobozzz

Also fixed a typo in the documentation

Added `data` as last param to not break the API, even if I think passing the `Segment` as first argument (as before) would better for future evolutions

2024-10-25 12:42 UTC, DimaDemchenko requested changes

2024-10-25 12:42 UTC, DimaDemchenko commented on packages/p2p-media-loader-core/src/p2p/peer.ts
> +            request.data as ArrayBuffer
Please remove the `as ArrayBuffer` type assertion and refactor the `isWrongSegment` condition for improved clarity. The revised check  ensures that request.data exists
```
  const isWrongSegment = 
    !request.data ||
    downloadingContext.request.segment.externalId !== command.i ||
    downloadingContext.requestId !== command.r;
```

```suggestion
            request.data
```

2024-10-28 07:17 UTC, Chocobozzz commented
Thanks for the review, it's fixed!

2024-10-28 12:46 UTC, DimaDemchenko approved these changes

2024-10-28 12:47 UTC, merged